package com.grababite.backend.controllers;

import com.grababite.backend.models.College;
import com.grababite.backend.services.CollegeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

// @RestController combines @Controller and @ResponseBody, meaning
// every method returns a domain object instead of a view, and the domain
// object is converted directly into JSON/XML.
@RestController
// @RequestMapping specifies the base URL path for all methods in this controller.
@RequestMapping("/api/colleges")
public class CollegeController {

    // @Autowired injects an instance of CollegeService.
    @Autowired
    private CollegeService collegeService;

    /**
     * GET /api/colleges
     * Retrieves a list of all colleges.
     * @return A list of College objects.
     */
    @GetMapping
    public List<College> getAllColleges() {
        return collegeService.getAllColleges();
    }

    /**
     * GET /api/colleges/{id}
     * Retrieves a single college by its ID.
     * @param id The UUID of the college to retrieve.
     * @return ResponseEntity with the College object and HTTP status 200 OK,
     * or 404 Not Found if the college does not exist.
     */
    @GetMapping("/{id}")
    public ResponseEntity<College> getCollegeById(@PathVariable UUID id) {
        return collegeService.getCollegeById(id)
                .map(ResponseEntity::ok) // If found, return 200 OK with college
                .orElse(ResponseEntity.notFound().build()); // If not found, return 404 Not Found
    }

    /**
     * POST /api/colleges
     * Creates a new college.
     * @param college The College object to create (sent in the request body as JSON).
     * @return ResponseEntity with the created College object and HTTP status 201 Created.
     */
    @PostMapping
    public ResponseEntity<College> createCollege(@RequestBody College college) {
        // When creating a new college, the ID is typically generated by the database.
        // Ensure the incoming college object does not have an ID set, or it will attempt to update.
        // For UUIDs with GenerationType.AUTO, Hibernate will handle generation on save.
        College createdCollege = collegeService.createCollege(college);
        return new ResponseEntity<>(createdCollege, HttpStatus.CREATED);
    }

    /**
     * PUT /api/colleges/{id}
     * Updates an existing college.
     * @param id The UUID of the college to update.
     * @param collegeDetails The College object with updated details (sent in request body).
     * @return ResponseEntity with the updated College object and HTTP status 200 OK,
     * or 404 Not Found if the college does not exist.
     */
    @PutMapping("/{id}")
    public ResponseEntity<College> updateCollege(@PathVariable UUID id, @RequestBody College collegeDetails) {
        College updatedCollege = collegeService.updateCollege(id, collegeDetails);
        if (updatedCollege != null) {
            return ResponseEntity.ok(updatedCollege);
        }
        return ResponseEntity.notFound().build();
    }

    /**
     * DELETE /api/colleges/{id}
     * Deletes a college by its ID.
     * @param id The UUID of the college to delete.
     * @return ResponseEntity with HTTP status 204 No Content if deleted,
     * or 404 Not Found if the college does not exist.
     */
    @DeleteMapping("/{id}")
    public ResponseEntity<HttpStatus> deleteCollege(@PathVariable UUID id) {
        boolean deleted = collegeService.deleteCollege(id);
        if (deleted) {
            return new ResponseEntity<>(HttpStatus.NO_CONTENT); // 204 No Content on successful deletion
        }
        return new ResponseEntity<>(HttpStatus.NOT_FOUND); // 404 Not Found if college not found
    }
}
