package com.grababite.backend.services;

import com.grababite.backend.models.Cafeteria;
import com.grababite.backend.models.College; // Import College entity
import com.grababite.backend.repositories.CafeteriaRepository;
import com.grababite.backend.repositories.CollegeRepository; // Import CollegeRepository
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

// @Service annotation marks this class as a Spring service component,
// making it eligible for Spring's component scanning and dependency injection.
@Service
public class CafeteriaService {

    // @Autowired injects an instance of CafeteriaRepository.
    // Spring will automatically find and provide the implementation.
    @Autowired
    private CafeteriaRepository cafeteriaRepository;

    // @Autowired injects an instance of CollegeRepository to retrieve College objects
    // when creating or updating Cafeterias that are linked to a College.
    @Autowired
    private CollegeRepository collegeRepository;

    /**
     * Retrieves a list of all cafeterias from the database.
     * @return A list of Cafeteria objects.
     */
    public List<Cafeteria> getAllCafeterias() {
        return cafeteriaRepository.findAll();
    }

    /**
     * Retrieves a single cafeteria by its ID.
     * @param id The UUID of the cafeteria to retrieve.
     * @return An Optional containing the Cafeteria if found, or empty if not.
     */
    public Optional<Cafeteria> getCafeteriaById(UUID id) {
        return cafeteriaRepository.findById(id);
    }

    /**
     * Saves a new cafeteria or updates an existing one in the database.
     * If the cafeteria object has a non-null ID that exists in the DB, it updates.
     * Otherwise, it creates a new entry.
     * The associated College object must be set on the Cafeteria object before calling this.
     * @param cafeteria The Cafeteria object to save.
     * @return The saved Cafeteria object (with its ID populated if new).
     */
    public Cafeteria createCafeteria(Cafeteria cafeteria) {
        // Ensure that the cafeteriaId is generated by the database if it's a new entity.
        // For UUIDs with GenerationType.AUTO, Spring/Hibernate handles this.
        return cafeteriaRepository.save(cafeteria);
    }

    /**
     * Updates an existing cafeteria.
     * @param id The UUID of the cafeteria to update.
     * @param cafeteriaDetails The Cafeteria object with updated details.
     * This object may or may not contain an updated College reference.
     * @return The updated Cafeteria object, or null if the cafeteria was not found.
     */
    public Cafeteria updateCafeteria(UUID id, Cafeteria cafeteriaDetails) {
        return cafeteriaRepository.findById(id).map(cafeteria -> {
            // Update basic fields
            cafeteria.setName(cafeteriaDetails.getName());
            cafeteria.setLocation(cafeteriaDetails.getLocation());
            cafeteria.setIsOpen(cafeteriaDetails.getIsOpen());

            // Update the associated College if a new one is provided in cafeteriaDetails
            if (cafeteriaDetails.getCollege() != null) {
                // It's good practice to re-fetch the College from the DB to ensure it's managed
                // and to prevent detached entity errors, especially if only an ID was passed.
                // However, in this service, the controller is expected to pass a fully
                // managed College object (or null if no change).
                Optional<College> existingCollege = collegeRepository.findById(cafeteriaDetails.getCollege().getCollegeId());
                existingCollege.ifPresent(cafeteria::setCollege);
            }

            // Save the updated cafeteria
            return cafeteriaRepository.save(cafeteria);
        }).orElse(null);
    }

    /**
     * Deletes a cafeteria by its ID.
     * @param id The UUID of the cafeteria to delete.
     * @return true if the cafeteria was deleted, false otherwise.
     */
    public boolean deleteCafeteria(UUID id) {
        if (cafeteriaRepository.existsById(id)) {
            cafeteriaRepository.deleteById(id);
            return true;
        }
        return false;
    }
}
