package com.grababite.backend.services;

import com.grababite.backend.models.College;
import com.grababite.backend.repositories.CollegeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

// @Service annotation marks this class as a Spring service component,
// making it eligible for Spring's component scanning and dependency injection.
@Service
public class CollegeService {

    // @Autowired injects an instance of CollegeRepository.
    // Spring will automatically find and provide the implementation.
    @Autowired
    private CollegeRepository collegeRepository;

    /**
     * Retrieves a list of all colleges from the database.
     * @return A list of College objects.
     */
    public List<College> getAllColleges() {
        return collegeRepository.findAll();
    }

    /**
     * Retrieves a single college by its ID.
     * @param id The UUID of the college to retrieve.
     * @return An Optional containing the College if found, or empty if not.
     */
    public Optional<College> getCollegeById(UUID id) {
        return collegeRepository.findById(id);
    }

    /**
     * Saves a new college or updates an existing one in the database.
     * If the college object has a non-null ID that exists in the DB, it updates.
     * Otherwise, it creates a new entry.
     * @param college The College object to save.
     * @return The saved College object (with its ID populated if new).
     */
    public College createCollege(College college) {
        // Ensure that the collegeId is generated by the database if it's a new entity.
        // For UUIDs with GenerationType.AUTO, Spring/Hibernate handles this.
        return collegeRepository.save(college);
    }

    /**
     * Updates an existing college.
     * @param id The UUID of the college to update.
     * @param collegeDetails The College object with updated details.
     * @return The updated College object, or null if the college was not found.
     */
    public College updateCollege(UUID id, College collegeDetails) {
        return collegeRepository.findById(id).map(college -> {
            college.setCollegeName(collegeDetails.getCollegeName());
            college.setAddress(collegeDetails.getAddress());
            // Update audit fields if necessary, though AuditModel handles some
            return collegeRepository.save(college);
        }).orElse(null);
    }

    /**
     * Deletes a college by its ID.
     * @param id The UUID of the college to delete.
     * @return true if the college was deleted, false otherwise.
     */
    public boolean deleteCollege(UUID id) {
        if (collegeRepository.existsById(id)) {
            collegeRepository.deleteById(id);
            return true;
        }
        return false;
    }
}
